# NSPass Agent 监控配置示例
# 包含详细的代理进程监控配置，适用于不同环境

# 基础配置
server_id: "your-server-id-here"

# API通信配置
api:
  base_url: "https://api.nspass.com"
  token: "your-api-token-here"
  timeout: 30
  retry_count: 3
  retry_delay: 5
  tls: true
  tls_skip_verify: false

# 代理软件配置
proxy:
  bin_path: "/usr/local/bin"
  config_path: "/etc/nspass/proxy"
  enabled_types: ["shadowsocks", "trojan", "snell"]
  auto_start: true
  restart_on_fail: true

  # 进程监控配置
  monitor:
    enable: true                # 是否启用代理进程监控
    check_interval: 30         # 检查间隔（秒）
    restart_cooldown: 60       # 重启冷却时间（秒）
    max_restarts: 10           # 每小时最大重启次数
    health_timeout: 5          # 健康检查超时（秒）

# IPTables防火墙配置
iptables:
  enable: true
  backup_path: "/etc/nspass/iptables-backup"
  persistent_method: "iptables-save"
  chain_prefix: "NSPASS"

# 日志配置
logger:
  level: "info"
  format: "json"
  output: "both"
  file: "/var/log/nspass/agent.log"
  max_size: 100
  max_backups: 5
  max_age: 30
  compress: true

# 更新间隔配置
update_interval: 300  # API同步间隔（秒）

# WebSocket配置
websocket:
  enabled: true
  server_url: "ws://localhost:8080/ws"
  agent_id: "agent-001"
  heartbeat_interval: 30s
  metrics_interval: 60s
  reconnect_interval: 5s
  max_reconnect_attempts: 0  # 0表示无限重试

 