name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: 'v1.0.0'

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
    
    - name: Debug filesystem
      run: |
        echo "Current working directory:"
        pwd
        echo "Files in current directory:"
        ls -la
        echo "Proto directory exists?"
        ls -la proto || echo "Proto directory not found"
        echo "Proto files count:"
        find proto -name "*.proto" | wc -l || echo "Cannot count proto files"
        echo "First 10 proto files:"
        find proto -name "*.proto" | head -10 || echo "Cannot list proto files"
    
    - name: Generate Proto Files
      run: |
        make gen-proto
    
    - name: Build
      run: |
        make release VERSION=${{ github.ref_name || github.event.inputs.version }}
    
    - name: List build artifacts
      run: |
        echo "Build artifacts:"
        ls -la release/
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name || github.event.inputs.version }}
        name: NSPass Agent ${{ github.ref_name || github.event.inputs.version }}
        body_path: release/RELEASE_NOTES.md
        files: |
          release/*.tar.gz
          release/*.zip
          release/SHA256SUMS
        draft: false
        prerelease: false
        make_latest: true
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}