name: Release

on:
  push:
    tags:
      - 'v*'  # 匹配 v1.0.0, v2.1.3 等版本标签

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Get version
      id: get_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Building version: $VERSION"

    - name: Install protoc
      run: |
        curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v25.1/protoc-25.1-linux-x86_64.zip
        unzip protoc-25.1-linux-x86_64.zip -d $HOME/.local
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Generate protobuf code
      run: |
        export PATH="$PATH:$(go env GOPATH)/bin"
        mkdir -p generated
        
        for proto in $(find proto -name "*.proto"); do
          protoc \
            --proto_path=proto \
            --proto_path=proto/google/protobuf \
            --go_out=generated \
            --go_opt=paths=source_relative \
            --go-grpc_out=generated \
            --go-grpc_opt=paths=source_relative \
            "$proto"
        done
        
        go mod tidy
        go build -o /tmp/test-build ./cmd/nspass-agent
        rm -f /tmp/test-build

    - name: Build binaries
      run: |
        mkdir -p dist
        
        VERSION=${{ steps.get_version.outputs.VERSION }}
        COMMIT=$(git rev-parse --short HEAD)
        BUILD_TIME=$(date -u '+%Y-%m-%d_%H:%M:%S')
        
        LDFLAGS="-w -s -X 'main.Version=${VERSION}' -X 'main.Commit=${COMMIT}' -X 'main.BuildTime=${BUILD_TIME}'"
        
        # 只构建Linux平台的不同架构
        platforms=(
          "linux/amd64"
          "linux/arm64" 
          "linux/386"
          "linux/arm"
        )
        
        for platform in "${platforms[@]}"; do
          GOOS=${platform%/*}
          GOARCH=${platform#*/}
          output_name="nspass-agent-${GOOS}-${GOARCH}"
          
          echo "Building for $GOOS/$GOARCH..."
          CGO_ENABLED=0 GOOS=$GOOS GOARCH=$GOARCH \
            go build -ldflags "$LDFLAGS" -o "dist/$output_name" ./cmd/nspass-agent
        done
        
        # 创建压缩包
        cd dist
        for binary in nspass-agent-*; do
          tar -czf "${binary}.tar.gz" "$binary"
        done

    - name: Generate changelog
      id: changelog
      run: |
        PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD~1 2>/dev/null || echo "")
        CURRENT_TAG=${{ steps.get_version.outputs.VERSION }}
        
        echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
        echo "## 更新内容" >> $GITHUB_OUTPUT
        echo "" >> $GITHUB_OUTPUT
        
        if [ -n "$PREVIOUS_TAG" ]; then
          echo "### 自 $PREVIOUS_TAG 以来的变更:" >> $GITHUB_OUTPUT
          git log --pretty=format:"- %s (%h)" $PREVIOUS_TAG..HEAD >> $GITHUB_OUTPUT
        else
          echo "### 初始版本发布" >> $GITHUB_OUTPUT
          git log --pretty=format:"- %s (%h)" >> $GITHUB_OUTPUT
        fi
        
        echo "" >> $GITHUB_OUTPUT
        echo "## 支持的平台" >> $GITHUB_OUTPUT
        echo "- Linux (amd64, arm64, 386, arm)" >> $GITHUB_OUTPUT
        echo "" >> $GITHUB_OUTPUT
        echo "## 安装说明" >> $GITHUB_OUTPUT
        echo "1. 下载对应架构的二进制文件" >> $GITHUB_OUTPUT
        echo "2. 解压文件: \`tar -xzf nspass-agent-linux-*.tar.gz\`" >> $GITHUB_OUTPUT
        echo "3. 将二进制文件移动到PATH目录中" >> $GITHUB_OUTPUT
        echo "4. 参考文档配置和使用" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Generate checksums
      run: |
        cd dist
        sha256sum *.tar.gz > checksums.txt

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        name: Release ${{ steps.get_version.outputs.VERSION }}
        body: ${{ steps.changelog.outputs.CHANGELOG }}
        draft: false
        prerelease: false
        files: |
          dist/*.tar.gz
          dist/checksums.txt
        token: ${{ secrets.GITHUB_TOKEN }} 